FROM registry.gitlab.com/neurochaintech/core/env_dev/release:latest

MAINTAINER trax Omar Givernaud
LABEL Description "Generic Bot Image"

# update this line to regen image: 001

USER neuro
WORKDIR /home/neuro
RUN mkdir conf
COPY build/src/main main
COPY testnet/bot.json conf/bot.json
COPY testnet/data.0.testnet conf/data.0.testnet
COPY utils/dockers/entrypoint.sh entrypoint.sh

# cleanup
RUN ./main --version
CMD ["./entrypoint.sh"]
