ARG DOCKER_BUILD_TYPE=registry.gitlab.com/neurochaintech/build/release:latest
FROM $DOCKER_BUILD_TYPE

MAINTAINER trax Omar Givernaud
LABEL Description "Generic bot"

USER neuro
COPY build/src/main main
COPY testnet/data.0.testnet /home/neuro/data.0.testnet

# cleanup
RUN du -sh /
RUN rm -r ./build
RUN rm -r ~/.hunter
RUN du -sh /
CMD ["./main", "-c", "testnet/bot.json"]
