FROM registry.gitlab.com/neurochaintech/core:latest

MAINTAINER trax Omar Givernaud
LABEL Description "Bot docker image with js faucet"

USER root

USER neuro

RUN mkdir -p /home/neuro/db || echo ok

# Faucet
RUN wget https://gitlab.com/neurochaintech/neurochain-faucet/-/jobs/artifacts/v1.0.1/download?job=build -O build.zip && \
unzip build.zip && \
rm build.zip && \
mv build faucet
